services:
  api:
    build:
      context: .
      dockerfile: apps/restapi/Dockerfile
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/todo
      REDIS_URL: redis://redis:6379
  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    ports:
      - "3000:80"
    environment:
      VITE_API_URL: http://localhost:5000 # For browser-side calls
    depends_on:
      - api
  postgres:
    image: postgres:15-alpine
    container_name: todo-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todo
    ports:
      - "5432:5432"
    volumes:
      - todo_postgres_data:/var/lib/postgresql/data

  redis:
    image: redis/redis-stack:latest
    container_name: my-redis-instance
    ports:
      - "6379:6379"
      - "8002:8001"
    volumes:
      - todo_redis_data:/data
    restart: always

volumes:
  todo_postgres_data:
  todo_redis_data:
