services:
  postgres:
    image: postgres:15-alpine
    container_name: todo-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todo
    ports:
      - "5432:5432"
    volumes:
      - todo_postgres_data:/var/lib/postgresql/data

  redis:
    image: redis/redis-stack:latest
    container_name: my-redis-instance
    ports:
      - "6379:6379"
      - "8002:8001"
    volumes:
      - todo_redis_data:/data
    restart: always

volumes:
  todo_postgres_data:
  todo_redis_data:
